FROM mcr.microsoft.com/vscode/devcontainers/java:0-11-bullseye

RUN su vscode -c "source /usr/local/sdkman/bin/sdkman-init.sh && sdk install gradle 7.4.2"

RUN su vscode -c "source /usr/local/sdkman/bin/sdkman-init.sh && sdk install groovy 3.0.7"